# Generated by Django 4.1.3 on 2023-10-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_description_menu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='Description',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
